<?php

namespace CommonBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * FosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FosUserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param bool $enable
     * @return QueryBuilder
     */
    public function getQueryBuilder($enable = true)
    {
        $queryBuilder = $this->createQueryBuilder('q');
        $queryBuilder->where('q.enabled = :enabled')->setParameter('enabled', $enable);

        return $queryBuilder;
    }

    /**
     * @param $username
     * @param $id
     * @return int
     */
    public function isUnique($username, $id)
    {
        $result = $this->createQueryBuilder('q')
            ->select('q')
            ->where('q.username = :username')
            ->andWhere('q.id != :id')
            ->setParameters([
                'id' => $id,
                'username' => $username
            ])
            ->getQuery()
            ->getResult();

        return count($result);
    }
}
