<?php

namespace CommonBundle\Repository;

/**
 * IdleMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdleMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
