<?php

namespace CommonBundle\Repository;

use CommonBundle\Constants\IdleStatus;
use Doctrine\ORM\QueryBuilder;

/**
 * IdleApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdleApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getQueryBuilder()
    {
        return $this->createQueryBuilder('q');
    }

    /**
     * @param $cId
     * @return mixed
     */
    public function findByCategory($cId)
    {
        $result = $this->createQueryBuilder('q')
            ->leftJoin('q.IdleCategory', 'ic')
            ->where('q.status = :status');

        if ($cId != 0) {
            $result = $result
                ->andWhere('ic.id = :cId')
                ->setParameter('cId', $cId);
        }
        $result = $result
            ->setParameter('status', IdleStatus::ONLINE)
            ->getQuery()
            ->getResult();
        return $result;
    }
}
