<?php

namespace CommonBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * IdleApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdleApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getQueryBuilder()
    {
        return $this->createQueryBuilder('q');
    }

    /**
     * @param $cId
     * @return mixed
     */
    public function findByCategory($cId){
        return $this->createQueryBuilder('q')
            ->leftJoin('q.IdleCategory', 'ic')
            ->where('ic.id = :cId')
            ->andWhere('q.status = :status')
            ->setParameters(['cId' => $cId, 'status' => 1])
            ->getQuery()
            ->getResult();
    }
}
