<?php

namespace CommonBundle\Repository;

/**
 * IdleProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdleProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
