<?php

namespace CommonBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * MatchInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchInfoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getQueryBuilder()
    {
        return $this->createQueryBuilder('q')
            ->orderBy('q.topAt', 'desc')
            ->addOrderBy('q.endAt', 'desc');
    }

    /**
     * @param $cId
     * @param $keyword
     * @param $currentSortOrder
     * @return QueryBuilder|mixed
     */
    public function searchByCategory($cId, $keyword, $currentSortOrder)
    {
        $result = $this->createQueryBuilder('q')
            ->leftJoin('q.MatchCategory', 'm')
            ->where('q.title LIKE :title')
            ->setParameter('title', "%{$keyword}%")
            ->orderBy('q.topAt', 'desc')
            ->addOrderBy('q.endAt', 'desc');

        if ($cId != 0) {
            $result = $result
                ->andWhere('m.id = :cId')
                ->setParameter('cId', $cId);
        }

        if ($currentSortOrder != "null") {
            $result = $result
                ->addOrderBy('q.createdAt', $currentSortOrder);
        }

        $result = $result
            ->getQuery()
            ->getResult();
        return $result;
    }
}
