<?php

namespace CommonBundle\Repository;

/**
 * MatchApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
