<?php

namespace CommonBundle\Repository;

/**
 * SayLoveMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SayLoveMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
