<?php

namespace CommonBundle\Repository;

/**
 * SayLoveMessageCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SayLoveMessageCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
