<?php

namespace CommonBundle\Repository;

/**
 * TopicCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
