<?php

namespace CommonBundle\Repository;

use CommonBundle\Entity\WeappUserApiKey;
use Doctrine\ORM\NonUniqueResultException;

/**
 * WeappUserApiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeappUserApiKeyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $apiKey
     * @return WeappUserApiKey|null
     */
    public function findOneByApiKey($apiKey)
    {
        try {
            $queryBuilder = $this->createQueryBuilder('q');
            $queryBuilder->select('q', 'm')->innerJoin('q.WeappUser', 'm');
            $queryBuilder->where('q.apiKey = :apiKey')->setParameter('apiKey', $apiKey);
            return $queryBuilder->getQuery()->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
            return null;
        }
    }
}
