<?php

namespace CommonBundle\Repository;

/**
 * WeappUserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeappUserProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
