<?php

namespace CommonBundle\Repository;

use CommonBundle\Entity\WeappUser;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\QueryBuilder;

/**
 * WeappUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeappUserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getQueryBuilder()
    {
        return $this->createQueryBuilder('q');
    }

    /**
     * @param string $username
     * @return WeappUser|null
     */
    public function findOneByUsername(string $username)
    {
        try {
            $queryBuilder = $this->getQueryBuilder();
            $queryBuilder->where('q.username = :username')->setParameter('username', $username);
            return $queryBuilder->getQuery()->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
            return null;
        }
    }
}
