services:
    ### Exception Listener ###
    CommonBundle\EventListener\RequestListener:
        arguments: ['@translator']
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    ### Exception Listener ###
    CommonBundle\EventListener\ExceptionListener:
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # jwt event listener
    api.event_listener.jwt:
        class: CommonBundle\EventListener\JWTEventListener
        calls:
            - [ setContainer, ['@service_container'] ]
        tags:
            - { name: kernel.event_subscriber }

    api.event_listener.jwt_invalid:
        class: CommonBundle\EventListener\JWTInvalidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }

    # hepler
    CommonBundle\Helpers\CommonRedis:
        arguments: ['%redis_host%', '%redis_port%', '%redis_password%']

    CommonBundle\Helpers\CommonHelper:
        arguments: [ "@service_container" ]

    # service
    CommonBundle\Services\CommonService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\ProfileService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\UserService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\CollegeService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\ProfessionalService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\IdleCategoryService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\MatchCategoryService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\MatchInfoService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\BannerService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\SendMsgService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\IdleApplicationService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\PageService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\TopicService:
        arguments: [ "@service_container" ]

    CommonBundle\Services\SMSService:
        arguments:
            - '%SUBMAIL_APPID%'
            - '%SUBMAIL_APPKEY%'
