CommonBundle\Entity\MatchApplication:
    type: entity
    table: weapp_match_application
    repositoryClass: CommonBundle\Repository\MatchApplicationRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        teamName:
            type: string
            nullable: true
            options:
                comment: 队名
        currentStatus:
            type: text
            nullable: true
            options:
                comment: 现状
        skill:
            type: text
            nullable: true
            options:
                comment: 技能要求
        experience:
            type: text
            nullable: true
            options:
                comment: 经验要求
        people:
            type: integer
            options:
                comment: 人数
                default: 0
        totalPeople:
            type: integer
            options:
                comment: 总人数
                default: 0
        joinEndAt:
            type: datetime
            nullable: true
            options:
                comment: 加入队伍截止时间
        extra:
            type: text
            nullable: true
        isSponsor:
            type: boolean
            options:
                comment: 是否发起人
        skills:
            type: text
            nullable: true
            options:
                comment: 技能
        matchExperience:
            type: text
            nullable: true
            options:
                comment: 比赛经验
        contact:
            type: text
            nullable: true
            options:
                comment: 联系方式
        isLock:
            type: boolean
            options:
                comment: 是否锁定
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        Parent:
            targetEntity: CommonBundle\Entity\MatchApplication
            inversedBy: Children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: SET NULL
        MatchInfo:
            targetEntity: CommonBundle\Entity\MatchInfo
            inversedBy: MatchApplication
            joinColumn:
                name: weapp_match_info_id
                referencedColumnName: id
                onDelete: SET NULL
        Profile:
            targetEntity: CommonBundle\Entity\WeappUserProfile
            inversedBy: MatchApplication
            joinColumn:
                name: profile_id
                referencedColumnName: id
                onDelete: SET NULL
    oneToMany:
        Children:
            targetEntity: CommonBundle\Entity\MatchApplication
            mappedBy: Parent
