services:
    ### Security ####
    WeappApiBundle\Security\ApiKeyUserProvider:
        arguments:
            - '@doctrine'

    WeappApiBundle\Security\ApiKeyAuthenticator:
        arguments:
            - '@doctrine'
            - '@annotation_reader'

    ### Event Listener ###
    WeappApiBundle\EventListener\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 250 }

    WeappApiBundle\EventListener\RequestEventListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    ### Exception Listener ###
    WeappApiBundle\EventListener\ExceptionListener:
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
